FRAME_HEIGHT = 8.0
ASPECT_RATIO = 1.0
FRAME_WIDTH = FRAME_HEIGHT * ASPECT_RATIO

FRAME_Y_RADIUS = FRAME_HEIGHT / 2
FRAME_X_RADIUS = FRAME_WIDTH / 2

ORIGIN = (0.0, 0.0, 0.0)
UP = (0.0, 1.0, 0.0)
DOWN = (0.0, -1.0, 0.0)
LEFT = (-1.0, 0.0, 0.0)
RIGHT = (1.0, 0.0, 0.0)
IN = (0.0, 0.0, -1.0)
OUT = (0.0, 0.0, 1.0)

TOP = (0.0, FRAME_Y_RADIUS, 0.0)
BOTTOM = (0.0, -FRAME_Y_RADIUS, 0.0)
LEFT_SIDE = (-FRAME_X_RADIUS, 0.0, 0.0)
RIGHT_SIDE = (FRAME_X_RADIUS, 0.0, 0.0)

UL = (-FRAME_X_RADIUS, FRAME_Y_RADIUS, 0.0)
UR = (FRAME_X_RADIUS, FRAME_Y_RADIUS, 0.0)
DL = (-FRAME_X_RADIUS, -FRAME_Y_RADIUS, 0.0)
DR = (FRAME_X_RADIUS, -FRAME_Y_RADIUS, 0.0)

SMALL_BUFF = 0.1
MED_SMALL_BUFF = 0.25
DEFAULT_MOBJECT_TO_EDGE_BUFF = 0.5
DEFAULT_MOBJECT_TO_MOBJECT_BUFF = 0.25

DEFAULT_PIXEL_WIDTH = 1080
DEFAULT_PIXEL_HEIGHT = 1080
DEFAULT_FPS = 30
DEFAULT_CAMERA_Z = 10.0
SCALE_FACTOR = 50.0


def ue_to_motion(x):
    return x / SCALE_FACTOR


def motion_to_ue(x):
    return x * SCALE_FACTOR


__all__ = [
    "FRAME_HEIGHT",
    "ASPECT_RATIO",
    "FRAME_WIDTH",
    "FRAME_Y_RADIUS",
    "FRAME_X_RADIUS",
    "ORIGIN",
    "UP",
    "DOWN",
    "LEFT",
    "RIGHT",
    "IN",
    "OUT",
    "TOP",
    "BOTTOM",
    "LEFT_SIDE",
    "RIGHT_SIDE",
    "UL",
    "UR",
    "DL",
    "DR",
    "SMALL_BUFF",
    "MED_SMALL_BUFF",
    "DEFAULT_MOBJECT_TO_EDGE_BUFF",
    "DEFAULT_MOBJECT_TO_MOBJECT_BUFF",
    "DEFAULT_PIXEL_WIDTH",
    "DEFAULT_PIXEL_HEIGHT",
    "DEFAULT_FPS",
    "DEFAULT_CAMERA_Z",
    "SCALE_FACTOR",
    "ue_to_motion",
    "motion_to_ue",
]
